### ISSUE TITLE
YARP 3.0 upgrade path

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#83]
Following https://github.com/roboticslab-uc3m/questions-and-answers/issues/65 (forward compat with YARP 3.x), https://github.com/roboticslab-uc3m/questions-and-answers/issues/78/https://github.com/roboticslab-uc3m/questions-and-answers/issues/82 (upgrade and require YCM v0.10+) and https://github.com/roboticslab-uc3m/questions-and-answers/issues/73 (migrating to Xenial builds in Travis), minimum required YARP version is going to be bumped from v2.3.70 to v3.0 soon enough. This issue will track code cleanup (remove pre-3.0 stuff), blockers and announcements.

**TODOs**

- Drop `find_package(YARP 2.3.70 REQUIRED)` fallbacks ([ref](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/95f65ff0b144ce4f2907fe4f4a6999d9ddf15258/CMakeLists.txt#L44-L46)).

- List optional and required components ([ref](https://github.com/roboticslab-uc3m/speech/blob/43801e151b9fdf20fc08d082fa10f116a97c7323/CMakeLists.txt#L41-L42), see also https://github.com/roboticslab-uc3m/questions-and-answers/issues/65#issuecomment-405119846 and https://github.com/roboticslab-uc3m/speech/issues/27).

- Update required YARP version in `doc/<repo>-install.md`.

- Remove version checks such as `#if YARP_VERSION_MAJOR != 3` in C++ and CMake code (e.g. https://github.com/roboticslab-uc3m/yarp-devices/commit/2af42cd5538f6be2d72b377efe1cc87c80e2a34f, https://github.com/roboticslab-uc3m/yarp-devices/issues/180).

- Fix C++/CMake deprecation warnings (check Travis builds).

- Rename local C++ implementation files regarding motor interfaces (e.g. *IControlMode2Impl.cpp* would become *IControlModeImpl.cpp*).

- Delete pre-v3.0 jobs in *.travis.yml* (delete the cache).

- Explore YARP [v3.0.0](https://github.com/robotology/yarp/releases/tag/v3.0.0) and [v3.0.1](https://github.com/robotology/yarp/releases/tag/v3.0.1) release notes, adopt new features (conditionally enable [v3.1.0](https://github.com/robotology/yarp/releases/tag/v3.1.0) and [v3.1.1](https://github.com/robotology/yarp/releases/tag/v3.1.1)).

- Tag the last pre-v3.0 commit.

- Upgrade robot on-board PCs.

- Review install guides, e.g. some CMake options have been renamed, removed, made optional or changed defaults ([ref](https://github.com/roboticslab-uc3m/installation-guides/blob/23ee6bd052ceb405f443726973bdd7a73d58fa98/install-yarp.md)).

**Blockers** (mostly related to a recent OpenNI2->RGBDSensor device migration, https://github.com/roboticslab-uc3m/vision/issues/83)

- [x] https://github.com/roboticslab-uc3m/teo-configuration-files/issues/16: update TEO's depth camera-related .xml files
- [x] https://github.com/roboticslab-uc3m/vision/issues/85: frame resolution mismatch bug
- [x] https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/92: YARP v2.3.72.1-v3.1.0 bug, missing interface implementation

**Comment by PeterBowman** [comment]
TEO's PCs now run YARP 3.1.1. Note that teo-head is a Trusty system, whereas manipulation and locomotion already moved on to Xenial.

**Comment by PeterBowman** [comment]
Since all blockers have been resolved, I'm going to gradually start enforcing the YARP 3.0+ requisite in several repositories. Please `git pull` to the latest `master` branch or check out YARP's v3.0.1 git tag. It is recommended to uninstall first.

cc @roboticslab-uc3m

**Comment by PeterBowman** [comment]
Since latest YARP master is now recommended, and YARP 3.1 was released shortly after YARP 3.0, I'm probably going to require YARP 3.1+ in a few repos (namely kin-dyn, openrave-yarp-plugins and yarp-devices). This will spare several version checks regarding features that had been added in v3.1 but weren't present at v3.0.x.

**Comment by PeterBowman** [comment]
> - Fix C++/CMake deprecation warnings (check Travis builds).

Notable changes:

* `yarp::os::ConstString` -> `std::string`
* `yarp::os::RateThread` -> `yarp::os::PeriodicThread`
  * `setRate()` -> `setPeriod()`
  * milliseconds -> seconds
* `VOCAB<N>` -> `yarp::os::createVocab()` (YARP 3.1)
* `IPositionControl2` -> `IPositionControl` and so on
* Arch-dependent `addInt()`-like methods (https://github.com/robotology/yarp/pull/1677)
  ```
  grep -rnIP '(add|is|as|make)(Int|Double)' /path/to/src/root --exclude-dir{build,doc}
  find /path/to/src/root -type f -exec sed -i -r 's/(add|is|as|make)Int/\1Int32/g' {} \+
  find /path/to/src/root -type f -exec sed -i -r 's/(add|is|as|make)Double/\1Float64/g' {} \+
  ```
* `YARP_HAS_MATH_LIB` -> `YARP_math_FOUND` (CMake code)

**Comment by PeterBowman** [comment]
> Tag the last pre-v3.0 commit.

Done at most relevant repositories listed [here](https://github.com/roboticslab-uc3m/developer-manual/blob/6de663baba7e864470ad28ea3a1c33fc337440ed/appendix/repository-index.md#robotics-general), namely:

* [kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/pre-yarp3.0)
* [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/pre-yarp3.0)
* [project-generator](https://github.com/roboticslab-uc3m/project-generator/tree/pre-yarp3.0)
* [speech](https://github.com/roboticslab-uc3m/speech/tree/pre-yarp3.0)
* [tools](https://github.com/roboticslab-uc3m/tools/tree/pre-yarp3.0)
* [vision](https://github.com/roboticslab-uc3m/vision/tree/pre-yarp3.0)
* [yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices/tree/pre-yarp3.0)

Nothing more to do here, closing.
